// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuS4HX8noBE3jNQycV4nIj9ZRDv-t_G9A',
    appId: '1:991486017291:web:a102f4e0c54cdbd09b6c0e',
    messagingSenderId: '991486017291',
    projectId: 'my-image-gallery-87ed7',
    authDomain: 'my-image-gallery-87ed7.firebaseapp.com',
    storageBucket: 'my-image-gallery-87ed7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxNWaY4FcBAEXGHdqBLlKVqFY-WXVlX6M',
    appId: '1:991486017291:android:ed47a4b4bed95a7c9b6c0e',
    messagingSenderId: '991486017291',
    projectId: 'my-image-gallery-87ed7',
    storageBucket: 'my-image-gallery-87ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjUIQ1UyYllqateptT0OP6VErMuvGjw2U',
    appId: '1:991486017291:ios:7d68c3b0159c29db9b6c0e',
    messagingSenderId: '991486017291',
    projectId: 'my-image-gallery-87ed7',
    storageBucket: 'my-image-gallery-87ed7.appspot.com',
    iosBundleId: 'com.example.myImageGallery',
  );
}
